
-- ADVANCED DATABASE TECHNIQUES PROJECT
-- Data Warehouse DDL: RESTAURANT_DW  (Star Schema)
-- Student ID: 10218 // Group:11B

-- NOTE: This file contains the DDL exported from Oracle via DBeaver. Run as SYS or DBA user.

-- The schema includes:
--   Dimensions: DIM_DATE, DIM_RESTAURANT, DIM_MENUITEM, DIM_CUSTOMER
--   Fact table:  FACT_SALES  // 10,000 rows loaded via SQL Loader

--DDL PART:

-- DROP USER RESTAURANT_DW;

CREATE USER RESTAURANT_DW
-- IDENTIFIED BY <password>
;

CREATE TABLE "RESTAURANT_DW"."DIM_CUSTOMER" 
   (	"CUSTOMERID" NUMBER, 
	"FULLNAME" VARCHAR2(100), 
	"LOYALTYTIER" VARCHAR2(20), 
	 PRIMARY KEY ("CUSTOMERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "RESTAURANT_DW"."DIM_DATE" 
   (	"DATEID" NUMBER, 
	"FULLDATE" DATE NOT NULL ENABLE, 
	"YEAR" NUMBER(4,0), 
	"QUARTER" NUMBER(1,0), 
	"MONTH" NUMBER(2,0), 
	"DAYOFWEEK" VARCHAR2(15), 
	 PRIMARY KEY ("DATEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "RESTAURANT_DW"."DIM_MENUITEM" 
   (	"ITEMID" NUMBER, 
	"ITEMNAME" VARCHAR2(100), 
	"CATEGORYNAME" VARCHAR2(50), 
	"CURRENTPRICE" NUMBER(10,2), 
	 PRIMARY KEY ("ITEMID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "RESTAURANT_DW"."DIM_RESTAURANT" 
   (	"RESTAURANTID" NUMBER, 
	"RESTNAME" VARCHAR2(100), 
	"CITYNAME" VARCHAR2(100), 
	"REGIONNAME" VARCHAR2(100), 
	 PRIMARY KEY ("RESTAURANTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "RESTAURANT_DW"."FACT_SALES" 
   (	"SALEID" NUMBER, 
	"DATEID" NUMBER, 
	"ITEMID" NUMBER, 
	"CUSTOMERID" NUMBER, 
	"QUANTITYSOLD" NUMBER, 
	"TOTALREVENUE" NUMBER(10,2), 
	"RESTAURANTID" NUMBER, 
	 PRIMARY KEY ("SALEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "RESTAURANT_DW"."FACT_SALES" ADD CONSTRAINT "FK_SALES_DATE" FOREIGN KEY ("DATEID")
	  REFERENCES "RESTAURANT_DW"."DIM_DATE" ("DATEID") ENABLE;
  ALTER TABLE "RESTAURANT_DW"."FACT_SALES" ADD CONSTRAINT "FK_SALES_ITEM" FOREIGN KEY ("ITEMID")
	  REFERENCES "RESTAURANT_DW"."DIM_MENUITEM" ("ITEMID") ENABLE;
  ALTER TABLE "RESTAURANT_DW"."FACT_SALES" ADD CONSTRAINT "FK_SALES_CUSTOMER" FOREIGN KEY ("CUSTOMERID")
	  REFERENCES "RESTAURANT_DW"."DIM_CUSTOMER" ("CUSTOMERID") ENABLE;
  ALTER TABLE "RESTAURANT_DW"."FACT_SALES" ADD CONSTRAINT "FK_SALES_REST" FOREIGN KEY ("RESTAURANTID")
	  REFERENCES "RESTAURANT_DW"."DIM_RESTAURANT" ("RESTAURANTID") ENABLE;
;