
-- ADVANCED DATABASE TECHNIQUES PROJECT
-- Operational Database DDL: RESTARUANT_DB
-- Student ID: 10218 // Group: 11B

-- NOTE: This file contains the DDL exported from Oracle via DBeaver. Run as SYS or DBA user.

-- The schema includes the following 15 tables:
--   1. REGIONS
--   2. CITIES
--   3. RESTAURANTS
--   4. EMPLOYEES
--   5. CUSTOMERS
--   6. CATEGORIES
--   7. MENUITEMS
--   8. INGREDIENTS
--   9. RECIPES
--  10. INVENTORY
--  11. ORDERS
--  12. ORDERDETAILS
--  13. SUPPLIERS
--  14. PURCHASEORDERS
--  15. PURCHASEORDERDETAILS

--DDL PART:


-- DROP USER RESTARUANT_DB;

CREATE USER RESTARUANT_DB
-- IDENTIFIED BY <password>
;


CREATE TABLE "RESTARUANT_DB"."REGIONS" 
   (	"REGIONID" NUMBER, 
	"REGIONNAME" VARCHAR2(100) NOT NULL ENABLE, 
	 PRIMARY KEY ("REGIONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";


CREATE TABLE "RESTARUANT_DB"."CITIES" 
   (	"CITYID" NUMBER, 
	"REGIONID" NUMBER, 
	"CITYNAME" VARCHAR2(100) NOT NULL ENABLE, 
	 PRIMARY KEY ("CITYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";

ALTER TABLE "RESTARUANT_DB"."CITIES" 
  ADD FOREIGN KEY ("REGIONID")
  REFERENCES "RESTARUANT_DB"."REGIONS" ("REGIONID") ENABLE;


CREATE TABLE "RESTARUANT_DB"."RESTAURANTS" 
   (	"RESTAURANTID" NUMBER, 
	"CITYID" NUMBER, 
	"RESTNAME" VARCHAR2(100) NOT NULL ENABLE, 
	"ADDRESS" VARCHAR2(255), 
	 PRIMARY KEY ("RESTAURANTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";

ALTER TABLE "RESTARUANT_DB"."RESTAURANTS" 
  ADD FOREIGN KEY ("CITYID")
  REFERENCES "RESTARUANT_DB"."CITIES" ("CITYID") ENABLE;


CREATE TABLE "RESTARUANT_DB"."EMPLOYEES" 
   (	"EMPLOYEEID" NUMBER, 
	"RESTAURANTID" NUMBER, 
	"FIRSTNAME" VARCHAR2(50), 
	"LASTNAME" VARCHAR2(50), 
	"JOBROLE" VARCHAR2(50), 
	"SALARY" NUMBER(10,2), 
	 PRIMARY KEY ("EMPLOYEEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";

ALTER TABLE "RESTARUANT_DB"."EMPLOYEES" 
  ADD FOREIGN KEY ("RESTAURANTID")
  REFERENCES "RESTARUANT_DB"."RESTAURANTS" ("RESTAURANTID") ENABLE;


CREATE TABLE "RESTARUANT_DB"."CUSTOMERS" 
   (	"CUSTOMERID" NUMBER, 
	"FIRSTNAME" VARCHAR2(50), 
	"LASTNAME" VARCHAR2(50), 
	"EMAIL" VARCHAR2(100), 
	"LOYALTYPOINTS" NUMBER DEFAULT 0, 
	 PRIMARY KEY ("CUSTOMERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";


CREATE TABLE "RESTARUANT_DB"."SUPPLIERS" 
   (	"SUPPLIERID" NUMBER, 
	"SUPPNAME" VARCHAR2(100) NOT NULL ENABLE, 
	"CONTACTPHONE" VARCHAR2(20), 
	 PRIMARY KEY ("SUPPLIERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";


CREATE TABLE "RESTARUANT_DB"."CATEGORIES" 
   (	"CATEGORYID" NUMBER, 
	"CATNAME" VARCHAR2(50) NOT NULL ENABLE, 
	 PRIMARY KEY ("CATEGORYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";


CREATE TABLE "RESTARUANT_DB"."MENUITEMS" 
   (	"ITEMID" NUMBER, 
	"CATEGORYID" NUMBER, 
	"ITEMNAME" VARCHAR2(100) NOT NULL ENABLE, 
	"PRICE" NUMBER(10,2) NOT NULL ENABLE, 
	 PRIMARY KEY ("ITEMID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";

ALTER TABLE "RESTARUANT_DB"."MENUITEMS" 
  ADD FOREIGN KEY ("CATEGORYID")
  REFERENCES "RESTARUANT_DB"."CATEGORIES" ("CATEGORYID") ENABLE;


CREATE TABLE "RESTARUANT_DB"."INGREDIENTS" 
   (	"INGREDIENTID" NUMBER, 
	"INGREDNAME" VARCHAR2(100) NOT NULL ENABLE, 
	"UNITOFMEASURE" VARCHAR2(20), 
	 PRIMARY KEY ("INGREDIENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";


CREATE TABLE "RESTARUANT_DB"."RECIPES" 
   (	"RECIPEID" NUMBER, 
	"ITEMID" NUMBER, 
	"INGREDIENTID" NUMBER, 
	"QUANTITYREQUIRED" NUMBER(10,2), 
	 PRIMARY KEY ("RECIPEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";

ALTER TABLE "RESTARUANT_DB"."RECIPES" 
  ADD FOREIGN KEY ("ITEMID")
  REFERENCES "RESTARUANT_DB"."MENUITEMS" ("ITEMID") ENABLE;
ALTER TABLE "RESTARUANT_DB"."RECIPES" 
  ADD FOREIGN KEY ("INGREDIENTID")
  REFERENCES "RESTARUANT_DB"."INGREDIENTS" ("INGREDIENTID") ENABLE;


CREATE TABLE "RESTARUANT_DB"."INVENTORY" 
   (	"INVENTORYID" NUMBER, 
	"RESTAURANTID" NUMBER, 
	"INGREDIENTID" NUMBER, 
	"STOCKLEVEL" NUMBER(10,2), 
	 PRIMARY KEY ("INVENTORYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";

ALTER TABLE "RESTARUANT_DB"."INVENTORY" 
  ADD FOREIGN KEY ("RESTAURANTID")
  REFERENCES "RESTARUANT_DB"."RESTAURANTS" ("RESTAURANTID") ENABLE;
ALTER TABLE "RESTARUANT_DB"."INVENTORY" 
  ADD FOREIGN KEY ("INGREDIENTID")
  REFERENCES "RESTARUANT_DB"."INGREDIENTS" ("INGREDIENTID") ENABLE;


CREATE TABLE "RESTARUANT_DB"."ORDERS" 
   (	"ORDERID" NUMBER, 
	"RESTAURANTID" NUMBER, 
	"CUSTOMERID" NUMBER, 
	"ORDERDATE" DATE NOT NULL ENABLE, 
	"TOTALAMOUNT" NUMBER(10,2), 
	 PRIMARY KEY ("ORDERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";

ALTER TABLE "RESTARUANT_DB"."ORDERS" 
  ADD FOREIGN KEY ("RESTAURANTID")
  REFERENCES "RESTARUANT_DB"."RESTAURANTS" ("RESTAURANTID") ENABLE;
ALTER TABLE "RESTARUANT_DB"."ORDERS" 
  ADD FOREIGN KEY ("CUSTOMERID")
  REFERENCES "RESTARUANT_DB"."CUSTOMERS" ("CUSTOMERID") ENABLE;


CREATE TABLE "RESTARUANT_DB"."ORDERDETAILS" 
   (	"ORDERDETAILID" NUMBER, 
	"ORDERID" NUMBER, 
	"ITEMID" NUMBER, 
	"QUANTITY" NUMBER NOT NULL ENABLE, 
	"SUBTOTAL" NUMBER(10,2), 
	 PRIMARY KEY ("ORDERDETAILID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";

ALTER TABLE "RESTARUANT_DB"."ORDERDETAILS" 
  ADD FOREIGN KEY ("ORDERID")
  REFERENCES "RESTARUANT_DB"."ORDERS" ("ORDERID") ENABLE;
ALTER TABLE "RESTARUANT_DB"."ORDERDETAILS" 
  ADD FOREIGN KEY ("ITEMID")
  REFERENCES "RESTARUANT_DB"."MENUITEMS" ("ITEMID") ENABLE;


CREATE TABLE "RESTARUANT_DB"."PURCHASEORDERS" 
   (	"PO_ID" NUMBER, 
	"RESTAURANTID" NUMBER, 
	"SUPPLIERID" NUMBER, 
	"PODATE" DATE NOT NULL ENABLE, 
	 PRIMARY KEY ("PO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";

ALTER TABLE "RESTARUANT_DB"."PURCHASEORDERS" 
  ADD FOREIGN KEY ("RESTAURANTID")
  REFERENCES "RESTARUANT_DB"."RESTAURANTS" ("RESTAURANTID") ENABLE;
ALTER TABLE "RESTARUANT_DB"."PURCHASEORDERS" 
  ADD FOREIGN KEY ("SUPPLIERID")
  REFERENCES "RESTARUANT_DB"."SUPPLIERS" ("SUPPLIERID") ENABLE;


CREATE TABLE "RESTARUANT_DB"."PURCHASEORDERDETAILS" 
   (	"PODETAILID" NUMBER, 
	"PO_ID" NUMBER, 
	"INGREDIENTID" NUMBER, 
	"QUANTITY" NUMBER(10,2), 
	"UNITCOST" NUMBER(10,2), 
	 PRIMARY KEY ("PODETAILID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";

ALTER TABLE "RESTARUANT_DB"."PURCHASEORDERDETAILS" 
  ADD FOREIGN KEY ("PO_ID")
  REFERENCES "RESTARUANT_DB"."PURCHASEORDERS" ("PO_ID") ENABLE;
ALTER TABLE "RESTARUANT_DB"."PURCHASEORDERDETAILS" 
  ADD FOREIGN KEY ("INGREDIENTID")
  REFERENCES "RESTARUANT_DB"."INGREDIENTS" ("INGREDIENTID") ENABLE;

